-- +goose Up
CREATE TABLE notification_attempts (
  notification_attempt_id text PRIMARY KEY,
  alert_id text REFERENCES alerts(alert_id) ON DELETE SET NULL,
  alert_recipient_id text REFERENCES alert_recipients(alert_recipient_id) ON DELETE SET NULL,
  account_id text NOT NULL REFERENCES accounts(account_id) ON DELETE RESTRICT,
  site_id text REFERENCES sites(site_id) ON DELETE SET NULL,
  device_id text REFERENCES devices(device_id) ON DELETE SET NULL,
  channel text NOT NULL DEFAULT 'email',
  status text NOT NULL DEFAULT 'pending',
  template_key text NOT NULL,
  recipient_email text NOT NULL,
  recipient_email_normalized text NOT NULL,
  subject text,
  body_text text,
  body_html text,
  provider text,
  provider_message_id text,
  idempotency_key text NOT NULL,
  attempt_count integer NOT NULL DEFAULT 0,
  last_error text,
  not_before timestamptz,
  claimed_at timestamptz,
  sent_at timestamptz,
  failed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT notification_attempts_channel_check CHECK (channel IN ('email')),
  CONSTRAINT notification_attempts_status_check CHECK (status IN ('pending', 'claimed', 'sent', 'failed', 'suppressed', 'canceled')),
  CONSTRAINT notification_attempts_attempt_count_check CHECK (attempt_count >= 0),
  UNIQUE (idempotency_key)
);

CREATE INDEX notification_attempts_status_not_before_idx ON notification_attempts(status, not_before, created_at);
CREATE INDEX notification_attempts_alert_idx ON notification_attempts(alert_id) WHERE alert_id IS NOT NULL;
CREATE INDEX notification_attempts_recipient_idx ON notification_attempts(alert_recipient_id) WHERE alert_recipient_id IS NOT NULL;

CREATE TABLE notification_suppressions (
  notification_suppression_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_recipient_id text REFERENCES alert_recipients(alert_recipient_id) ON DELETE CASCADE,
  scope_key text NOT NULL,
  family text NOT NULL,
  suppressed_until timestamptz NOT NULL,
  reason_code text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT notification_suppressions_family_check CHECK (family IN ('device_disconnected', 'backup_failed_or_overdue', 'app_update_attention'))
);

CREATE INDEX notification_suppressions_scope_idx ON notification_suppressions(scope_key, family, suppressed_until DESC);
CREATE INDEX notification_suppressions_recipient_idx ON notification_suppressions(alert_recipient_id, family, suppressed_until DESC) WHERE alert_recipient_id IS NOT NULL;

-- +goose Down
DROP INDEX IF EXISTS notification_suppressions_recipient_idx;
DROP INDEX IF EXISTS notification_suppressions_scope_idx;
DROP TABLE IF EXISTS notification_suppressions;
DROP INDEX IF EXISTS notification_attempts_recipient_idx;
DROP INDEX IF EXISTS notification_attempts_alert_idx;
DROP INDEX IF EXISTS notification_attempts_status_not_before_idx;
DROP TABLE IF EXISTS notification_attempts;
